### ISSUE TITLE
Support the service.name in the payload

### ISSUE THREAD

**Issue by onimsha** [mindvalley/mv-opentelemetry#15]
At this moment, it seems the library does not have any method to set the `service.name` attribute. This is crucial since Honeycomb does several reports / query that involves the service name, and we need to know the lifespan of a request across multiple services, for example hitting API in the `api` application , then querying DB in the `academy` application etc.....

**Comment by maciej-szlosarczyk** [comment]
This cannot be really done, as per [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/semantic_conventions/README.md#service) - each service is a separate exacutable. But in #20 I added ability to add custom parameters, so you can add `[{"component", "academy"}]` to all DB traces on setup:

```ex
    :ok =
      MvOpentelemetry.register_tracer(:ecto,
        span_prefix: [:academy, :repo],
        default_attributes: [{"component", "academy"}]
      )
```
