### ISSUE TITLE
Thinking about dropping the field resolving events from the trace

### ISSUE THREAD

**Issue by onimsha** [mindvalley/mv-opentelemetry#16]
Currently we're tracing the field resolving event, although it's good to have more granularity in the trace, but i can see few disadvantage of this approach:  

* Making the trace hard to read if there are too many events. In some trace that we actually have in production, the amount of field resolving traces are thousands , and it's almost impossible to read it properly. It does not provide much value to us in that case.  
* If error happens for some request, usually it does not happen at the field resolving phase, but somewhere else, like calling external system ( for example DB). So it make senses to have less events in the trace, and focus on what important. 

So what i'm proposing is we remove the `[:absinthe, :resolve, :field, :start]` and `[:absinthe, :resolve, :field, :stop]` from the library. Then we can have less events per trace and also still able to gain visibility of the GraphQL request.

**Comment by maciej-szlosarczyk** [comment]
I am thinking that this would be best done with a [custom sampler](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#sampling). I will look into it.
